### ISSUE TITLE
Package ozon-repos-21-5.fc21.noarch.rpm is not signed

### ISSUE THREAD

**Issue by Jobava** [satya164/fedy#162]
Cannot run "yum update" or "dnf update" because of the error:

    Package ozon-repos-21-5.fc21.noarch.rpm is not signed

**Comment by satya164** [comment]
The issue is fixed now. Please try again.

**Comment by LeleDev** [comment]
Still getting the same error:

/var/cache/yum/x86_64/21/ozonos/packages/fedy-4.0.0-1.noarch.rpm: Header V4 RSA/SHA1 Signature, ID chiave b8c0fc22: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos


Retrieving GPG key error: [Errno 14] curl#37 - "Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos"

**Comment by satya164** [comment]
You can try the following,

```
sudo yum erase fedy
sudo yum clean expire-cache
sudo yum install http://goodies.ozon-os.com/repo/21/noarch/ozon-repos-21-5.fc21.noarch.rpm
sudo yum install http://goodies.ozon-os.com/repo/21/noarch/fedy-4.0.0-1.noarch.rpm
```

**Comment by LeleDev** [comment]
Solved, thank you!

**Comment by satya164** [comment]
Cool :D

**Comment by orlandoaleman** [comment]
Fixed here! Thanks
